// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
//   - protoc-gen-go-enum {{.Version}}
//   - protoc             {{.ProtocVersion}}
{{- if .IsDeprecated}}
// {{.Source}} is a deprecated file.
{{- else}}
// source: {{.Source}}
{{- end}}

package {{.Package}}

import (
	"github.com/go-playground/validator/v10"
	"go.uber.org/multierr"
)

func RegisterValidation(validate *validator.Validate) error {
	return multierr.Combine(
{{- range $e := .Enums}}
		validate.RegisterValidation("typing_{{snakecase $e.Name}}", func(fl validator.FieldLevel) bool {
			value, ok := fl.Field().Interface().({{$e.Name}})
			if !ok {
				return false
			}
			_, ok = {{$e.Name}}_name[int32(value)]
			return ok
		}),
{{- end}}
	)
}