// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
//   - protoc-gen-go-enum v0.0.1
//   - protoc             v3.21.2
// source: enum.proto

package examples

// __FooStatusMapping FooStatus mapping
var __FooStatusMapping = map[int]string{
	0: "00",
	1: "",
	2: "22",
	3: "33",
	4: "44",
}

// GetFooStatusDesc get mapping description
//
//	Foo 状态值, {"0":"00","1":"","2":"22","3":"33","4":"44"}
func GetFooStatusDesc(t int) string {
	return __FooStatusMapping[t]
}
