// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.1
// source: errnop/errno.proto

package errnop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// xx
	ErrorReason_unspecified ErrorReason = 0    // 未定义
	ErrorReason_bad_request ErrorReason = 1000 // 用户名或密码错误
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:    "unspecified",
		1000: "bad_request",
	}
	ErrorReason_value = map[string]int32{
		"unspecified": 0,
		"bad_request": 1000,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errnop_errno_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errnop_errno_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errnop_errno_proto_rawDescGZIP(), []int{0}
}

var File_errnop_errno_proto protoreflect.FileDescriptor

var file_errnop_errno_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x70, 0x2f, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x70, 0x2a, 0x30, 0x0a, 0x0b,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x75,
	0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0b,
	0x62, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0xe8, 0x07, 0x42, 0x29,
	0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x79, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_errnop_errno_proto_rawDescOnce sync.Once
	file_errnop_errno_proto_rawDescData = file_errnop_errno_proto_rawDesc
)

func file_errnop_errno_proto_rawDescGZIP() []byte {
	file_errnop_errno_proto_rawDescOnce.Do(func() {
		file_errnop_errno_proto_rawDescData = protoimpl.X.CompressGZIP(file_errnop_errno_proto_rawDescData)
	})
	return file_errnop_errno_proto_rawDescData
}

var file_errnop_errno_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errnop_errno_proto_goTypes = []any{
	(ErrorReason)(0), // 0: errnop.ErrorReason
}
var file_errnop_errno_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errnop_errno_proto_init() }
func file_errnop_errno_proto_init() {
	if File_errnop_errno_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errnop_errno_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errnop_errno_proto_goTypes,
		DependencyIndexes: file_errnop_errno_proto_depIdxs,
		EnumInfos:         file_errnop_errno_proto_enumTypes,
	}.Build()
	File_errnop_errno_proto = out.File
	file_errnop_errno_proto_rawDesc = nil
	file_errnop_errno_proto_goTypes = nil
	file_errnop_errno_proto_depIdxs = nil
}
