// Code generated by protoc-gen-go-errno. DO NOT EDIT.
// versions:
//   - protoc-gen-go-errno v0.1.2
//   - protoc              v5.28.1
// source: errnop/errno.proto

package errnop

import (
	fmt "fmt"
	errorx "github.com/things-go/dyn/errorx"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf

// Reference imports to suppress errors if they are not otherwise used.
var _ = errorx.New

func IsUnspecified(err error) bool {
	return errorx.EqualCode(err, 0)
}
func ErrUnspecified() *errorx.Error {
	return errorx.New(0, "未定义")
}
func IsBadRequest(err error) bool {
	return errorx.EqualCode(err, 1000)
}
func ErrBadRequest() *errorx.Error {
	return errorx.New(1000, "用户名或密码错误")
}
