// Code generated by protoc-gen-dyn-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-dyn-enum v1.0.0
//   - protoc                v5.28.1
// source: non_nested.proto

package enums

import (
	"strconv"
)

// Enum value label/mapping for NonNestedStatus.
var (
	__NonNestedStatus_xx_Label = map[NonNestedStatus]string{
		0: "未定义",
		1: "上",
		2: "下",
		3: "左",
		4: "右",
	}
	__NonNestedStatus_xx_Value = map[string]NonNestedStatus{
		"未定义": 0,
		"上":   1,
		"下":   2,
		"左":   3,
		"右":   4,
	}

	__NonNestedStatus_xx_Mapping = map[NonNestedStatus]string{
		0: "unspecified",
		1: "up",
		2: "down",
		3: "left",
		4: "right",
	}
	__NonNestedStatus_xx_Mapping_Value = map[string]NonNestedStatus{
		"unspecified": 0,
		"up":          1,
		"down":        2,
		"left":        3,
		"right":       4,
	}
)

// EnumCount the number of enum value.
func (NonNestedStatus) EnumCount() int {
	return 5
}

// IntoNumber returns the enum value as an integer.
func (x NonNestedStatus) IntoNumber() int32 {
	return int32(x)
}

// IntoNumberString returns the enum value as an integer string.
func (x NonNestedStatus) IntoNumberString() string {
	return strconv.FormatInt(int64(x), 10)
}

// EnumLabel the label of enum value.
// NonNestedStatus 状态值
// [0:未定义,1:上,2:下,3:左,4:右]
func (x NonNestedStatus) EnumLabel() string {
	return __NonNestedStatus_xx_Label[x]
}

// ParseEnumLabel parse the label.
// NonNestedStatus 状态值
// [0:未定义,1:上,2:下,3:左,4:右]
func (e *NonNestedStatus) ParseEnumLabel(s string) {
	*e = __NonNestedStatus_xx_Value[s]
}

// EnumMapping the mapping of enum value.
func (x NonNestedStatus) EnumMapping() string {
	return __NonNestedStatus_xx_Mapping[x]
}

// ParseEnumMapping parse the mapping.
func (e *NonNestedStatus) ParseEnumMapping(s string) {
	*e = __NonNestedStatus_xx_Mapping_Value[s]
}
