// Code generated by "stringer -type=Deploy -linecomment"; DO NOT EDIT.

package deploy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Local-1]
	_ = x[Develop-2]
	_ = x[Debug-3]
	_ = x[Uat-4]
	_ = x[Production-5]
}

const _Deploy_name = "nonelocaldevdebuguatprod"

var _Deploy_index = [...]uint8{0, 4, 9, 12, 17, 20, 24}

func (i Deploy) String() string {
	if i < 0 || i >= Deploy(len(_Deploy_index)-1) {
		return "Deploy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Deploy_name[_Deploy_index[i]:_Deploy_index[i+1]]
}
