// Code generated by errno-gen. DO NOT EDIT.
// version: v0.0.1
package errno

import (
	errors "github.com/things-go/dyn/errorx"
)

// ErrTimeout 操作超时
// `BizError`业务错误: 1000
func ErrTimeout(opts ...errors.Option) error {
	return errors.New(int32(Timeout), Timeout.String(), opts...)
}

// ErrUserNotExist 用户不存在
// `BizError`业务错误: 1001
func ErrUserNotExist(opts ...errors.Option) error {
	return errors.New(int32(UserNotExist), UserNotExist.String(), opts...)
}
