// Code generated by "stringer -type BizError -linecomment"; DO NOT EDIT.

package errno

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Timeout-1000]
	_ = x[UserNotExist-1001]
}

const _BizError_name = "操作超时用户不存在"

var _BizError_index = [...]uint8{0, 12, 27}

func (i BizError) String() string {
	i -= 1000
	if i < 0 || i >= BizError(len(_BizError_index)-1) {
		return "BizError(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _BizError_name[_BizError_index[i]:_BizError_index[i+1]]
}
