// Code generated by protoc-gen-dyn-errno. DO NOT EDIT.
// versions:
//   - protoc-gen-dyn-errno v0.0.1
//   - protoc                 v4.25.3
// source: errno.proto

package errno

import (
	errors "github.com/things-go/dyn/errorx"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = errors.New

func ErrInternalServer(opts ...errors.Option) *errors.Error {
	return errors.New(500, "服务器错误", opts...)
}
func ErrTimeout(opts ...errors.Option) *errors.Error {
	return errors.New(1000, "操作超时", opts...)
}
