// Code generated by protoc-gen-dyn-errno. DO NOT EDIT.
// versions:
//   - protoc-gen-dyn-errno {{.Version}}
//   - protoc                 {{.ProtocVersion}}
{{- if .IsDeprecated}}
// {{.Source}} is a deprecated file.
{{- else}}
// source: {{.Source}}
{{- end}}

package {{.Package}}

import (
	errors "{{.Epk}}"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ =	errors.New

{{- range $e := .Errors}}
{{$enumName := $e.Name}}
{{ range .Values }}
func Err{{.CamelValue}}(opts ...errors.Option) *errors.Error {
	return errors.New({{.Code}}, "{{.Message}}", opts...)
}
{{- end }}
{{- end }}