// Code generated by protoc-gen-dyn-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-dyn-enum {{.Version}}
//   - protoc                {{.ProtocVersion}}
{{- if .IsDeprecated}}
// {{.Source}} is a deprecated file.
{{- else}}
// source: {{.Source}}
{{- end}}

package {{.Package}}

import (
	"strconv"
)

{{- range $e := .Enums}}
{{$enumName := $e.Name}}
{{$enumValuePrefix := $e.Name}}
{{if $e.MessageName}}
{{$enumName = printf "%s_%s" $e.MessageName $e.Name}}
{{$enumValuePrefix = $e.MessageName}}
{{end}}

// Enum value label/mapping for {{$enumName}}.
var (
	__{{$enumName}}_xx_Label = map[{{$enumName}}]string{
	{{- range $ee := $e.Values}}
		{{if $ee.IsDuplicate}}// Duplicate value: {{end}}{{$ee.Number}}: "{{$ee.Label}}",
	{{- end}}
	}
	__{{$enumName}}_xx_Value = map[string]{{$enumName}}{
	{{- range $ee := $e.Values}}
		"{{$ee.Label}}": {{$ee.Number}},
	{{- end}}
	}
{{if $e.HasMapping }}
	__{{$enumName}}_xx_Mapping = map[{{$enumName}}]string{
	{{- range $ee := $e.Values}}
		{{if $ee.IsDuplicate}}// Duplicate value: {{end}}{{$ee.Number}}: "{{$ee.Mapping}}",
	{{- end}}
	}
	__{{$enumName}}_xx_Mapping_Value = map[string]{{$enumName}}{
	{{- range $ee := $e.Values}}
		"{{$ee.Mapping}}": {{$ee.Number}},
	{{- end}}
	}
{{end}}
)

// EnumCount the number of enum value.
func ({{$enumName}}) EnumCount() int {
	return {{len $e.Values}}
}

// IntoNumber returns the enum value as an integer.
func (x {{$enumName}}) IntoNumber() int32 {
	return int32(x)
}

// IntoNumberString returns the enum value as an integer string.
func (x {{$enumName}}) IntoNumberString() string {
	return strconv.FormatInt(int64(x), 10)
}

// EnumLabel the label of enum value.
{{$e.Comment}}
func (x {{$enumName}}) EnumLabel() string {
	return __{{$enumName}}_xx_Label[x]
}

// ParseEnumLabel parse the label.
{{$e.Comment}}
func (e *{{$enumName}}) ParseEnumLabel(s string ) {
	*e = __{{$enumName}}_xx_Value[s]
}

{{if $e.HasMapping }}
// EnumMapping the mapping of enum value.
func (x {{$enumName}}) EnumMapping() string {
	return __{{$enumName}}_xx_Mapping[x]
}

// ParseEnumMapping parse the mapping.
func (e *{{$enumName}}) ParseEnumMapping(s string ) {
	*e = __{{$enumName}}_xx_Mapping_Value[s]
}
{{end}}

{{- end}}

