// Code generated by protoc-gen-dyn-resty. DO NOT EDIT.
// versions:
// - protoc-gen-dyn-resty v0.2.0
// - protoc                v4.24.0
// source: hello.proto

package examples

import (
	context "context"
	errors "errors"
	http "github.com/things-go/dyn/transport/http"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = errors.New
var _ = context.TODO
var _ = http.NewClient

// GreeterHTTPClient
type GreeterHTTPClient interface {
	// SayHello Sends a hello
	// I am a trailing comment
	SayHello(context.Context, *HelloRequest, ...http.CallOption) (*HelloReply, error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(c *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{
		cc: c,
	}
}

// SayHello Sends a hello
// I am a trailing comment
func (c *GreeterHTTPClientImpl) SayHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var err error
	var resp HelloReply

	settings := c.cc.CallSetting("/v1/hello", opts...)
	path := settings.Path
	err = c.cc.Invoke(ctx, "POST", path, req, &resp, settings)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
